defaults:
  aws:
    accessKeyId:        '...'
    secretAccessKey:    '...'
    region:             us-west-2
  app:
    # these must be in aws.region
    publicArtifactBucket: ...
    privateArtifactBucket: ...
  pulse:
    username:           '...'
    password:           '...'
