defaults:
  # defaults outlining all configuration options and some sane defaults
  app:
    component: hooks
    hookTableName: hooks_entities
    lastFireTableName: last_fire_3_entities
    queuesTableName: queues_entities
    scheduler:
      pollingDelay:   60000
  influx:
    connectionString: !env:optional INFLUX_CONNECTION
    maxDelay:         300
    maxPendingPoints: 300
  azure:
    accountId:        !env AZURE_ACCOUNT_ID
    cryptoKey:        !env AZURE_CRYPTO_KEY
  postgres:
    readDbUrl:        !env READ_DB_URL
    writeDbUrl:       !env WRITE_DB_URL
    dbCryptoKeys:     !env:json:optional DB_CRYPTO_KEYS
  taskcluster:
    rootUrl:          !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId:       !env TASKCLUSTER_CLIENT_ID
      accessToken:    !env TASKCLUSTER_ACCESS_TOKEN
  monitoring:
    level: !env:optional LEVEL
    errorConfig: !env:json:optional ERROR_CONFIG
  server:
    port:             !env:number PORT
    env:              !env NODE_ENV
    forceSSL:         !env:bool FORCE_SSL
    trustProxy:       !env:bool TRUST_PROXY
  pulse:
    username:       !env PULSE_USERNAME
    password:       !env PULSE_PASSWORD
    hostname:       !env PULSE_HOSTNAME
    vhost:          !env PULSE_VHOST
    # a list of regular expressions for exchanges that are prohibited
    denylist:
     # triggering a hook on task-created could create a "task bomb" that just spews
     # out tasks with no end, and isn't useful otherwise
     - exchange/taskcluster-queue/v1/task-created
     # changes to hooks themselves are internal and shouldn't trigger hooks
     - exchange/taskcluster-hooks/.*

  # new relic config (processed in services/prelude.js)
  newRelic: !env:json:optional NEW_RELIC

test:
  # See user-config-example.yml for secrets credentials required for tests
  taskcluster:
    rootUrl: "https://tc.example.com"

  app:
    component:        hooks-tests
    scheduler:
      pollingDelay:   5000
  postgres:
    dbCryptoKeys:
      - id: 'hooks'
        algo: 'aes-256'
        key: "aSdtIGJzdGFjayEgaGVsbG8gZnV0dXJlIHBlcnNvbgo="
  azure:
    accountId:        'pamplemousse'
    cryptoKey:        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
  server:
    port:             60401
    env:              development
    forceSSL:         false
    trustProxy:       false
  pulse:
    namespace:        'taskcluster-fake'
