defaults:
  app:
    statsComponent:               'secrets'

  # Taskcluster configuration
  taskcluster:
    rootUrl:                      !env TASKCLUSTER_ROOT_URL

    # Taskcluster credentials for this server, allowing access to the Azure table,
    # sentry, etc.
    credentials:
      clientId:                   !env TASKCLUSTER_CLIENT_ID
      accessToken:                !env TASKCLUSTER_ACCESS_TOKEN

  azure:
    # deprecated way to specify an encryption key
    cryptoKey:                    !env:optional AZURE_CRYPTO_KEY

  postgres:
    readDbUrl:                    !env READ_DB_URL
    writeDbUrl:                   !env WRITE_DB_URL
    dbCryptoKeys:                 !env:json:optional DB_CRYPTO_KEYS

  monitoring:
    level:                      !env:optional LEVEL
    errorConfig: !env:json:optional ERROR_CONFIG

  # Server configuration
  server:
    # Port to listen for requests on
    port:                           !env:number PORT

    # Environment 'development' or 'production'
    env:                            !env NODE_ENV
    # Force SSL, not useful when runnning locally
    forceSSL:                       !env:bool FORCE_SSL

    # Trust a forwarding proxy
    trustProxy:                   true

  # new relic config (processed in services/prelude.js)
  newRelic: !env:json:optional NEW_RELIC

test:
  taskcluster:
    rootUrl: "https://tc.example.com"

  app:
    statsComponent:               'test-queue'

  azure:
    cryptoKey:                    'CNcj2aOozdo7Pn+HEkAIixwninIwKnbYc6JPS9mNxZk='

  server:
    port:                         60415
    forceSSL:                     false
    env:                            'development'
    trustProxy:                     false
