---
defaults:
  app:
    exchangePrefix:              'v1/'
    cachePurgeExpirationDelay:   '- 1 hour'
    cacheTime:                   10

  monitoring:
    level: !env:optional LEVEL
    errorConfig: !env:json:optional ERROR_CONFIG

  server:
    # Port to listen for requests on
    port:                           !env:number PORT

    # Environment 'development' or 'production'
    env:                            !env NODE_ENV

    # Force SSL not useful when runnning locally
    forceSSL:                       !env:bool FORCE_SSL

    # Trust a forwarding proxy
    trustProxy:                     !env:bool TRUST_PROXY

  postgres:
    readDbUrl: !env READ_DB_URL
    writeDbUrl: !env WRITE_DB_URL

  taskcluster:
    rootUrl:                     !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId:                   !env TASKCLUSTER_CLIENT_ID
      accessToken:                !env TASKCLUSTER_ACCESS_TOKEN

  # new relic config (processed in services/prelude.js)
  newRelic: !env:json:optional NEW_RELIC

test:
  taskcluster:
    rootUrl: "https://tc.example.com"

  app:
    cachePurgeExpirationDelay:   '7 days'
    cacheTime:                   300    # safely long enough to finish a test

  server:
    port:                         60415
    forceSSL:                     false
    trustProxy:                   true
    env: development
