defaults:
  app:
    # Route prefix used to form custom routes on the form
    #  'route.<routePrefix>.<namespace>'
    routePrefix: 'index'

    # Name of pulse queue, if a non-exclusive queue is to be used.
    listenerQueueName: 'index/incoming-tasks2'

    # Time delay before expiring artifacts, in readable format, see:
    # taskcluster.fromNow, notice this should be negative!
    expirationDelay: '-1 day'

  postgres:
    readDbUrl: !env READ_DB_URL
    writeDbUrl: !env WRITE_DB_URL

  monitoring:
    level: !env:optional LEVEL
    errorConfig: !env:json:optional ERROR_CONFIG

  # Server configuration
  server:
    # Port to listen for requests on
    port: !env:number PORT

    # Environment 'development' or 'production'
    env: !env NODE_ENV

    forceSSL: !env:bool FORCE_SSL
    trustProxy: !env:bool TRUST_PROXY

  # Configuration of access to other taskcluster components
  taskcluster:
    # Taskcluster credentials for this server, these must have scopes:
    # auth:credentials, queue:*
    # (typically configured using environment variables)
    rootUrl: !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN

  # Pulse
  pulse:
    hostname: !env PULSE_HOSTNAME
    username: !env PULSE_USERNAME
    password: !env PULSE_PASSWORD
    vhost: !env PULSE_VHOST
    namespace: taskcluster-index

  # new relic config (processed in services/prelude.js)
  newRelic: !env:json:optional NEW_RELIC

test:
  taskcluster:
    rootUrl: "https://tc.example.com"
  app:
    listenerQueueName: 'test-queue'

  server:
    port: 60020
    env: development
    forceSSL: false
    trustProxy: false

  aws:
    region: 'us-west-2'

  pulse:
    namespace: 'taskcluster-fake'
